#!/usr/bin/env python

# Copyright (c) 2010, Fresno Pacific University
# Licensed under the New BSD license; see the LICENSE file for details.

import sys
from MoodleTools.mdl_server import mdl_server

command = mdl_server()
quit(command.main())
